### ISSUE TITLE
Bars without gradient don't render

### ISSUE THREAD

**Issue by amcdnl** [jask-oss/reaviz#76]
A bar chart with gradients and masks turned off doesn't render.

**Comment by totallymike** [comment]
I'm seeing this as well. Seems to be something related to chroma-js and how it brightens color values:
https://github.com/jask-oss/reaviz/blob/d2cccb035d001f67d4ead4c416ae601a9ff999aa/src/BarChart/BarSeries/Bar.tsx#L597

It seems this returns an object, which isn't handled correctly by framer-motion

**Comment by amcdnl** [comment]
Fixed that but the clip path seesm to be causing the issue

**Comment by totallymike** [comment]
I saw that the clip path was somehow affected as well. I think the funky color value is causing the animation to short-circuit before it can fix those things?

Disabling animation allows the bars to render, though you still get warnings in the console when you hover over a bar.

**Comment by amcdnl** [comment]
FYI - I published the change for the hover fix.

**Comment by totallymike** [comment]
Awesome! Thank you 👍

**Comment by mutsumiya** [comment]
Closing this b/c this has been fixed. Here is an example: https://reaviz.io/?path=/story/charts-bar-chart-vertical-single-series--custom-style
